accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register')
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # Home page with different user blogs.
    path('', views.index, name='index'),
    # Show all blogs.
    path('blogs/', views.blogs, name='blogs'),
    # Show individual blog posts of a blog.
    path('blogs/<int:blog_id>', views.blog, name='blog'),
    # Page for adding a new blog.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for adding a new blog post.
    path('new_blog_post/<int:blog_id>/', views.new_blog_post, name='new_blog_post'),
    # Page for editing a blog post.
    path('edit_blog_post/<int:blog_post_id>/', views.edit_blog_post, name='edit_blog_post'),
]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls'),)
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    """The blog of a user."""
    name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Blog_Post(models.Model):
    """Individual blog post."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.TextField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return [self.title, self.body]

blog/forms.py
from django import forms

from .models import Blog, Blog_Post

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']

class Blog_Post_Form(forms.ModelForm):
    class Meta:
        model = Blog_Post
        fields = ['title', 'body']
        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blog:index')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, Blog_Post
from .forms import BlogForm, Blog_Post_Form

def index(request):
    """The home page for My Blog."""
    return render(request, 'blog/index.html')


def blogs(request):
    """Display all blogs."""
    blogs = Blog.objects.all().select_related('owner')
    context = {'blogs': blogs, 'user': request.user}
    return render(request, 'blog/blogs.html', context)


def blog(request, blog_id):
    """Display all individual blog posts."""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blog_post_set.all()
    context = {'blog': blog, 'posts': posts, 'user': request.user}
    return render(request, 'blog/blog.html', context)

@login_required
def new_blog(request):
    """Add a new blog."""
    if request.method != 'POST':
        # No data submitted; create a blank from.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blog:blogs')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blog/new_blog.html', context)

@login_required
def new_blog_post(request, blog_id):
    """Add a new blog post."""
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # No data submitted; create a blank from.
        form = Blog_Post_Form()
    else:
        # POST data submitted; process data.
        form = Blog_Post_Form(data=request.POST)
        if form.is_valid():
            new_blog_post = form.save(commit=False)
            new_blog_post.blog = blog
            new_blog_post.save()
            return redirect('blog:blog', blog_id=blog.id)
    
    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blog/new_blog_post.html', context)

@login_required
def edit_blog_post(request, blog_post_id):
    """Edit a blog post."""
    blog_post = Blog_Post.objects.get(id=blog_post_id)
    blog = blog_post.blog
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current blog post.
        form = Blog_Post_Form(instance=blog_post)
    else:
        # POST data submitted; process data.
        form = Blog_Post_Form(instance=blog_post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:blog', blog_id=blog.id)
        
    context = {'blog_post': blog_post, 'blog': blog, 'form': form}
    return render(request, 'blog/edit_blog_post.html', context)


def check_blog_owner(blog, user):
    """Check if the blog is owned by the user."""
    if blog.owner != user:
        raise Http404

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog and Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
          Blog and Log</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blogs' %}">
              Blogs</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                  Register</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                  Log in</a></li>
          {% endif %}

        </ul> <!-- End of account-related links -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-secondary btn-sm'>
              Log out</button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %} 

{% block page_header %}
    <h1>{{  blog.name  }}</h1>
{% endblock page_header %}

{% block content %}
    {% if user == blog.owner %}
        <p>
            <a class="btn btn-primary" href="{% url 'blog:new_blog_post' blog.id %}" role="button">Add new blog post</a>

        </p>
    {% endif %}

    {% for post in posts %}
        <div class="card mb-3">
             <h5 class="card-header">
                {{ post.title }} ({{ post.date_added|date:'M d, Y'}})
                {% if user == blog.owner %}
                    <small>
                        <a class="btn btn-secondary btn-sm" href="{% url 'blog:edit_blog_post' post.id %}" role="button">Edit blog post</a>
                    </small>
                {% endif %}
             </h5>
              <div class="card-body">
                <p class="card-text">{{ post.body }}</p>
              </div>
        </div>

    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content %}

blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h1>Blogs</h1>
{% endblock page_header %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'blog:new_blog' %}" role="button">Add a new blog</a>

    <ul class="list-group border-bottom pb-2 mb-4">
        {% for blog in blogs %}
            <li class="list-group-item border-0">
                <a href="{% url 'blog:blog' blog.id %}" class="list-group-item list-group-item-action">{{ blog.name }} - by {{ blog.owner.username }}</a>
            </li>
        {% empty %}
            <li class="list-group-item border-0">No topics have been added yet.</li>
        {% endfor %}

    </ul>




{% endblock content%}

blog/templates/blog/edit_blog_post.html
{% extends "blog/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h1>Edit entry:</h1>
{% endblock page_header %}

{% block content %}

    <p>
        <a class="btn btn-secondary btn-sm" href="{% url 'blog:blog' blog.id %}" role="button">{{ blog.name }}</a>
    </p>

    <form action="{% url 'blog:edit_blog_post' blog_post.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save changes" %}
    </form>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Log your leaning.</h1>

            <p class="lead">Make your own blog, and keep a list of the 
                topics you're interested about. Whenever you learn, want to review, or
                talk about a topic, make a log summarizing what you're thinking about it.
            </p>

            {% if not user.is_authenticated %}
            <a class="btn btn-primary btn-lg mt-1"
                href="{% url 'accounts:register' %}">Register &raquo;</a>
            {% else %}
            <a class="btn btn-primary btn-lg mt-1"
                href="{% url 'blog:blogs' %}">Show blogs &raquo;</a>
            {% endif %}
        </div>
    </div>
{% endblock page_header %}

blog/templates/blog/new_blog.html
{% extends "blog/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add a new blog</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'blog:new_blog' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add blog" %}
    </form>
{% endblock content %}

blog/templates/blog/new_blog_post.html
{% extends "blog/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

<p>
    <a class="btn btn-secondary btn-sm" href="{% url 'blog:blog' blog.id %}" role="button">{{ blog.name }}</a>
</p>

    <p>Add new blog post</p>
    <form action="{% url 'blog:new_blog_post' blog.id%}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add blog" %}
    </form>

{% endblock content %}